# ワークフロー名
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
#===============================
# ECR にプッシュする時のActions
#===============================
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG --build-arg IMAGE_TAG=${IMAGE_TAG} .
        docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: test-ecs-deploy
        IMAGE_TAG: ${{ github.sha }}
#===============================
# ECS にデプロイする時のActions
#===============================
    - name: Render Amazon ECS task definition
      id: render-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: aws/task-definition.json
        container-name: app
        image: ${{ steps.login-ecr.outputs.registry }}/test-ecs-deploy:${{ github.sha }}
    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-container.outputs.task-definition }}
        service: ecs-service-common-ECSService-F6AJUTS66AQD-ECSService-14L7KJG3X4ROJ
        cluster: ecs-cluster-common-app